config/routes.rb
Rails.application.routes.draw do

resources :users

  get 'users/index' => 'users#index'

  get 'users/new' => 'users#new'

  get 'users/show' => 'users#show'

  get 'users/edit' => 'users#edit'

resources :posts

  get 'posts/:id/edit' => 'posts#edit'
 
  get 'posts' => 'posts#index'

  get 'posts/new' => 'posts#new'

  get 'posts/:id' => 'posts#show'

  post 'posts/' => 'posts#create'

  put 'posts/:id' => 'posts#update'

  delete 'posts/:id' => 'posts#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@post = Post.all
  end

  def new
  	@post = Post.new
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def create
    @post = Post.create(params.require(:post).permit(:title, :description, :travel_date))
  end
#   def create
#   	@posts = Post.new(user_params)
#     if post.save
#     	format.html {redirect_to @post, notice: 'post was successfully created.'}
#     	format.json { render :show, status: :created, location: @post }
#     else
#     	format.html { render :new }
#     	format.json { render json: @post.errors, status: :unproccessable_entity }
#     end
#end


# def update
#     respond_to do |format|
#       if post.update(post_params)
#         format.html { redirect_to post, notice: 'post was successfully updated.' }
#         format.json { render :show, status: :ok, location: post }
#       else
#         format.html { render :edit }
#         format.json { render json: post.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   def destroy
#     post.destroy
#     respond_to do |format|
#       format.html { redirect_to posts_url, notice: 'post was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all 
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def create
     user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
      if user.save
          session["user_id"] = user.id.to_s
          redirect_to posts_path
      else
          redirect_to new_user_path
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journal_helper.rb
module JournalHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelJournal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Journal#edit</h1>
<p>Find me in app/views/journal/edit.html.erb</p>

 <%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label	:images %><br>
    <%= f.text_field :images %>
  </div>
  
  <div class="date">
  	<%= f.label :date %><br>
  	<%= f.text_field :date %>
  </div>

 <div class="actions">
 	<%= f.submit %>
 </div>

<% end %>

app/views/posts/index.html.erb
<h1>Journal#index</h1>
<p>Find me in app/views/journal/index.html.erb</p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>post</th>
      <th>title</th>
      <th>description</th>
      <th>images</th>
      <th>travel date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.email %></td>
        <td><%= post.dob %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>Journal#new</h1>
<p>Find me in app/views/journal/new.html.erb</p>

<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label	:images %><br>
    <%= f.text_field :images %>
  </div>
  
  <div class="date">
  	<%= f.label :date %><br>
  	<%= f.text_field :date %>
  </div>

 <div class="actions">
 	<%= f.submit %>
 </div>

<% end %>

app/views/posts/show.html.erb
<h1>Journal#show</h1>
<p>Find me in app/views/journal/show.html.erb</p>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Iamges:</strong>
  <%= @post.images %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<!-- edit allows for you to edit an entry -->
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
  	<%= f.label :last_name %><br>
  	<%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>email</th>
      <th>first_name</th>
      <th>last_name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up:</h1>


<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
  	<%= f.label :last_name %><br>
  	<%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.dob %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>